# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/179iPNZbefbFg8ZinLv-pMn6GUIj1_x5p
"""

!pip install streamlit
!pip install pyngrok

import streamlit as st
from PIL import Image

# عنوان اپلیکیشن
st.title('Image Uploader Example')

# نوار کناری برای آپلود تصویر
st.sidebar.title('Upload an image')

# آپلود فایل تصویر
uploaded_file = st.sidebar.file_uploader("Choose an image...", type=["jpg", "png", "jpeg"])

# اگر فایل آپلود شد
if uploaded_file is not None:
    # باز کردن تصویر
    image = Image.open(uploaded_file)

    # نمایش تصویر در اپ
    st.image(image, caption='Uploaded Image.', use_column_width=True)

    # گرفتن عرض و ارتفاع تصویر
    width, height = image.size

    # چاپ عرض و ارتفاع تصویر
    st.write(f"Width: {width} pixels")
    st.write(f"Height: {height} pixels")

from pyngrok import ngrok

# پورت Streamlit رو تنظیم می‌کنیم (پیش‌فرض 8501 هست)
public_url = ngrok.connect(8501)

# شروع اجرای Streamlit
!streamlit run /content/your_script_name.py &

# نمایش URL عمومی برای دسترسی به اپ
public_url

from pyngrok import ngrok

# تنظیم authtoken برای ngrok
ngrok.set_auth_token('2wJxzycQQUUqI3l1oiTjm0IAX9o_43MBpkdK7Ak3caG4P9zYd')

# باز کردن تونل بر روی پورت 8501
public_url = ngrok.connect(8501)

# نمایش URL عمومی برای دسترسی به اپ
public_url

!streamlit run /content/your_script_name.py &

# Commented out IPython magic to ensure Python compatibility.
# # نوشتن کد استریم‌لیت داخل فایل
# %%writefile app.py
# import streamlit as st
# from PIL import Image
# 
# st.title('Image Uploader Example')
# st.sidebar.title('Upload an image')
# 
# uploaded_file = st.sidebar.file_uploader("Choose an image...", type=["jpg", "png", "jpeg"])
# 
# if uploaded_file is not None:
#     image = Image.open(uploaded_file)
#     st.image(image, caption='Uploaded Image.', use_column_width=True)
#     width, height = image.size
#     st.write(f"Width: {width} pixels")
#     st.write(f"Height: {height} pixels")
#

from pyngrok import ngrok
import os

# اجرای استریم‌لیت در پس‌زمینه
!streamlit run app.py &

# ایجاد تونل ngrok برای دسترسی به اپلیکیشن
public_url = ngrok.connect(8501)
public_url

import streamlit as st
from PIL import Image

# عنوان اپلیکیشن
st.title('Welcome to My Image App')

# ایجاد نوار کناری (sidebar) برای انتخاب گزینه‌ها
st.sidebar.title('Sidebar Example')

# ایجاد رادیو باتن‌ها برای انتخاب یک گزینه
option = st.sidebar.radio(
    "Choose an option:",
    ["Upload Image", "Show Info"]
)

# بخش آپلود تصویر (اگر گزینه 'Upload Image' انتخاب بشه)
if option == "Upload Image":
    uploaded_file = st.sidebar.file_uploader("Choose an image...", type=["jpg", "png", "jpeg"])

    if uploaded_file is not None:
        # باز کردن تصویر
        image = Image.open(uploaded_file)

        # نمایش تصویر در اپلیکیشن
        st.image(image, caption='Uploaded Image.', use_column_width=True)

        # گرفتن عرض و ارتفاع تصویر
        width, height = image.size

        # نمایش ابعاد تصویر
        st.write(f"Width: {width} pixels")
        st.write(f"Height: {height} pixels")

# بخش نمایش اطلاعات (اگر گزینه 'Show Info' انتخاب بشه)
elif option == "Show Info":
    st.write("This app allows you to upload and display images. Select 'Upload Image' from the sidebar to get started.")

from pyngrok import ngrok

# اجرای استریم‌لیت در پس‌زمینه
!streamlit run app.py &

# ایجاد تونل ngrok برای دسترسی به اپلیکیشن
public_url = ngrok.connect(8501)
public_url

import streamlit as st
from PIL import Image
import pandas as pd

# عنوان اپلیکیشن
st.title('Welcome to My Image and Data App')

# نوار کناری برای انتخاب بخش‌ها
st.sidebar.title('Sidebar Example')

option = st.sidebar.radio(
    "Choose an option:",
    ["Upload Image", "Show Info", "Submit Form", "Upload CSV"]
)

# بخش فرم
if option == "Submit Form":
    with st.sidebar.form(key='my_form'):
        st.text_input("Your Name:")
        st.selectbox("Your Age Range:", ["Under 20", "21-30", "31-40", "41-50", "Over 50"])
        submit_button = st.form_submit_button(label='Submit')

    if submit_button:
        st.write("Form submitted!")
        # اینجا می‌تونی مقادیر فرم رو ذخیره کنی یا عملیات دیگه‌ای انجام بدی

# بخش آپلود تصویر
elif option == "Upload Image":
    uploaded_file = st.sidebar.file_uploader("Choose an image...", type=["jpg", "png", "jpeg"])

    if uploaded_file is not None:
        image = Image.open(uploaded_file)
        st.image(image, caption='Uploaded Image.', use_column_width=True)
        width, height = image.size
        st.write(f"Width: {width} pixels")
        st.write(f"Height: {height} pixels")

# بخش نمایش اطلاعات
elif option == "Show Info":
    st.write("This app allows you to upload images, submit forms, and upload CSV files. Select an option from the sidebar.")

# بخش آپلود CSV
elif option == "Upload CSV":
    uploaded_csv = st.sidebar.file_uploader("Choose a CSV file...", type="csv")

    if uploaded_csv is not None:
        data = pd.read_csv(uploaded_csv)
        st.write("CSV Data:")
        st.write(data.head())  # نمایش 5 ردیف اول دیتای CSV

import streamlit as st
from PIL import Image
import pandas as pd

# عنوان اپلیکیشن
st.title('Welcome to My Image and Data App')

# نوار کناری برای انتخاب بخش‌ها
st.sidebar.title('Sidebar Example')

option = st.sidebar.radio(
    "Choose an option:",
    ["Upload Image", "Show Info", "Submit Form", "Upload CSV"]
)

# بخش فرم در نوار کناری
if option == "Submit Form":
    with st.sidebar.form(key='my_form'):
        name = st.text_input("Your Name:")
        age = st.selectbox("Your Age Range:", ["Under 20", "21-30", "31-40", "41-50", "Over 50"])
        submit_button = st.form_submit_button(label='Submit')

    if submit_button:
        st.write(f"Name: {name}")
        st.write(f"Age Range: {age}")
        st.write("Form submitted successfully!")

# بخش آپلود تصویر
elif option == "Upload Image":
    uploaded_file = st.sidebar.file_uploader("Choose an image...", type=["jpg", "png", "jpeg"])

    if uploaded_file is not None:
        image = Image.open(uploaded_file)
        st.image(image, caption='Uploaded Image.', use_column_width=True)
        width, height = image.size
        st.write(f"Width: {width} pixels")
        st.write(f"Height: {height} pixels")

# بخش نمایش اطلاعات
elif option == "Show Info":
    st.write("This app allows you to upload images, submit forms, and upload CSV files. Select an option from the sidebar.")

# بخش آپلود CSV
elif option == "Upload CSV":
    uploaded_csv = st.sidebar.file_uploader("Choose a CSV file...", type="csv")

    if uploaded_csv is not None:
        data = pd.read_csv(uploaded_csv)
        st.write("CSV Data:")
        st.write(data.head())  # نمایش 5 ردیف اول دیتای CSV

from pyngrok import ngrok

# اجرای Streamlit در پس‌زمینه
!streamlit run app.py &

# ایجاد تونل ngrok برای دسترسی به اپلیکیشن
public_url = ngrok.connect(8501)
public_url

import streamlit as st
from PIL import Image
import pandas as pd

# عنوان اپلیکیشن
st.title('Welcome to My Upload App')

# نوار کناری برای انتخاب بخش‌ها
st.sidebar.title('Sidebar Example')

# ابتدا اطلاعات مورد نیاز رو از کاربر بگیریم
st.sidebar.subheader("Enter Your Information:")
name = st.sidebar.text_input("Your Name:")
email = st.sidebar.text_input("Your Email:")
age = st.sidebar.selectbox("Your Age Range:", ["Under 20", "21-30", "31-40", "41-50", "Over 50"])

# حالا به کاربر اجازه می‌دهیم که انتخاب کند که چه فایلی می‌خواهد آپلود کند
st.sidebar.subheader("Choose a file to upload:")
file_option = st.sidebar.radio("Select file type", ("Upload Image", "Upload CSV", "None"))

# اگر کاربر گزینه "آپلود تصویر" رو انتخاب کنه
if file_option == "Upload Image":
    uploaded_file = st.sidebar.file_uploader("Choose an image...", type=["jpg", "png", "jpeg"])

    if uploaded_file is not None:
        image = Image.open(uploaded_file)
        st.image(image, caption='Uploaded Image.', use_column_width=True)
        width, height = image.size
        st.write(f"Width: {width} pixels")
        st.write(f"Height: {height} pixels")

# اگر کاربر گزینه "آپلود CSV" رو انتخاب کنه
elif file_option == "Upload CSV":
    uploaded_csv = st.sidebar.file_uploader("Choose a CSV file...", type="csv")

    if uploaded_csv is not None:
        data = pd.read_csv(uploaded_csv)
        st.write("CSV Data:")
        st.write(data.head())  # نمایش 5 ردیف اول دیتای CSV

# اگر هیچ فایل انتخاب نشه
elif file_option == "None":
    st.write("Please select a file type to upload.")

# نمایش اطلاعات وارد شده توسط کاربر
st.sidebar.subheader("Your Information:")
st.sidebar.write(f"Name: {name}")
st.sidebar.write(f"Email: {email}")
st.sidebar.write(f"Age Range: {age}")